---
title: "ssi_scores"
author: "Lily Zhao"
date: "2024-11-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggbump)
library(here)
library(grafify) 
```

```{r}

df_path <- here("raw_data", "2023_ssi_scores.csv")
df<- read_csv(df_path)
dfsr <- df %>% 
  select(1:4, starts_with("SSI.D")) %>% 
  mutate(og_total = rowSums(select(., starts_with("SSI.D")))) %>% 
   mutate(committment = rowSums(select(., c("SSI.D01", "SSI.D02", "SSI.D27")))) %>% 
  mutate(new_total= og_total- committment) %>%  #everything but committments 
  arrange(desc(og_total)) %>% 
  mutate(og_rank = row_number()) %>% 
    arrange(desc(new_total)) %>% 
  mutate(new_rank = row_number()) %>% 
  mutate(change_rank= og_rank-new_rank)

#changes ranks in the top 20 
dfsr_top20<-  dfsr %>% 
  filter(og_rank< 21) %>% 
  rename(official_score= og_total) %>% 
  rename(real_score= new_total) %>% 
  select(company_label, official_score, real_score, og_rank, new_rank, change_rank)
  
top20long <- dfsr_top20 %>%
  pivot_longer(cols = c(og_rank, new_rank), 
               names_to = "rank_type", 
               values_to = "rank") %>% 
  select(change_rank, company_label, rank_type, rank) %>% 
  mutate(rank = as.numeric(rank)) %>%
  mutate(change_cat = case_when(
    change_rank > 0 ~ "Relatively better \nthan appear",
    change_rank == 0 ~ "No change",
    change_rank < 0 ~ "Relatively worse \nthan appear"
  )) %>% 
  mutate(rank_label = case_when(
    rank_type == "og_rank" ~ "Official",
    rank_type == "new_rank" ~ "Less washed"
  )) %>%
  mutate(change_cat = factor(change_cat, levels = c("Relatively better \nthan appear", "No change", "Relatively worse \nthan appear")),
         rank_types = factor(rank_label, levels = c("Less washed", "Official")))

labels<-top20long %>% 
  filter(rank_types=="Less washed") 



# Plotting

my_theme <- theme_minimal(base_size = 12, base_family = "Helvetica") +
  theme(
    axis.text.x = element_text(face = "italic", angle = 0, vjust = 0.5, hjust = 0.5, size = 10),
    axis.text.y = element_text(face = "italic", size = 10),
    axis.title.x = element_text(face = "bold", size = 12),
    axis.title.y = element_text(face = "bold", size = 12),
    strip.text = element_text(size = 11),
    panel.grid = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.background = element_rect(fill = "white"), 
    plot.background = element_rect(fill = "white"), 
    panel.border = element_blank(),  
    legend.position = "bottom",
    legend.box = "vertical",
    legend.justification = "left",
    legend.box.just = "left",
    legend.title = element_text(face = "bold", size = 10),
    legend.text = element_text(size = 11),
    strip.background = element_blank(),
    strip.placement = "outside",
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10)
  )

orbldiv_colors <- c("#9E3D21","#DA6524", "#F0AC72", "#D8D4C9",  "#5789B6", "#4071A0", "#2B5B8A"  )



f1<-ggplot(top20long, aes(x = rank_label, y = rank, group = company_label)) +
  geom_bump(aes(color = change_rank)) +  
  geom_text(data = labels %>% 
              group_by(company_label) %>% 
              filter(rank == min(rank)),  
            aes(label = company_label),
            size = 4, hjust = .75, vjust = -.35, nudge_x = -0.01) + 
scale_color_gradientn(colors = orbldiv_colors)+
theme_minimal() +
  labs(x = "Rank type", y = "Ranking position") +
  facet_wrap(~change_cat) +
  scale_y_reverse(limits = c(20, 1), breaks = c(1, 5, 10, 20)) + 
  my_theme+
  theme(legend.position = "none", 
        axis.text.y = element_text(angle = 0, hjust = 1)) 


ggsave("figures/ssi_c_doesnt_count.png", plot = f1, width = 9, height = 5.5, dpi = 600)
```